project_name: lx

before:
  hooks:
    - go mod tidy

builds:
  - id: lx
    main: ./cmd/lx
    binary: lx
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    flags:
      - -trimpath
    ldflags:
      - -s -w -X github.com/rasros/lx/lx.Version={{.Version}}

archives:
  - id: archive
    builds:
      - lx
    format_overrides:
      - goos: windows
        format: zip
    files:
      - LICENSE
      - README.md

checksum:
  name_template: "checksums.txt"

changelog:
  use: git
  sort: desc
  filters:
    exclude:
      - '^docs:'
      - '^test:'

brews:
  - name: lx
    # If you want to host your tap in a separate repo, e.g. rasros/homebrew-tap:
    tap:
      owner: rasros
      name: homebrew-tap
    commit_author:
      name: goreleaser
      email: rasmus.s.ros@gmail.com
    homepage: "https://github.com/rasros/lx"
    description: "Format one or more files into Markdown-fenced blocks for LLM chat windows"
    license: "MIT"
    folder: Formula
    goarm: "7"
    dependencies: []
    install: |
      bin.install "lx"
    test: |
      system "#{bin}/lx", "--help"

release:
  # Uses GitHub Releases by default when repo is on GitHub and GITHUB_TOKEN is set
  prerelease: auto

